# Generated by Django 4.2.5 on 2023-10-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available')], default=0),
        ),
    ]
